### ISSUE TITLE
windows10 16299.371 nothing happened

### ISSUE THREAD

**Issue by Wubadao321** [mtivadar/windows10_ntfs_crash_dos#4]
may microsoft fixd it.

**Comment by mtivadar** [comment]
indeed, as I said in readme "Does not seem to reproduce on my current build: 10.0.16299 Build 16299 x64 "
seems fixed by microsoft, so I went public.

**Comment by mtivadar** [comment]
indeed, as I said in readme "Does not seem to reproduce on my current build: 10.0.16299 Build 16299 x64 "
seems fixed by microsoft, so I went public.

**Comment by VisibleReality** [comment]
Working for me on windows 10.0.16299.371
